buffer_mgr: buffer_mgr.c buffer_mgr_stat.c dberror.c FIFO.c LRU.c storage_mgr.c test_assign2_1.c CLOCK.c
	gcc -o buffer_mgr buffer_mgr.c buffer_mgr_stat.c dberror.c FIFO.c LRU.c CLOCK.c storage_mgr.c test_assign2_1.c -I.
clean: 
	rm -f *.o buffer_mgr
